apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: fhb-fis-o-rollback-transfer
  name: fhb-fis-o-rollback-transfer
data:
  application.properties: |-
    camel.springboot.tracing=false
    camel.component.servlet.mapping.enabled=true
    camel.component.servlet.mapping.context-path=/target/*
    camel.opentracing.encoding=true
    #sensitive.masking.ext=
    #headers.whitelist.ext=

    #External connectity (Bridges)
    ibs.bridge.endpoint=http4://fhb-fis-b-ibs-outbound.fhb-fis-dev.svc.cluster.local:8080/bridge/fhb-fis-b-ibs-outbound

    #Mapping Service
    mapping.url=http4://fhb-mapping-service:8080/target/Mock/Transform

    #Orch related stuff
    oab.deadEndpoint=log:foo?logMask=true

    sftp.host=sftp.api-test.fhb.com:22

    #allowed business exception to sftp
    sftp.allowed.services=mock

    server.undertow.io-threads=8
    server.undertow.worker-threads=50
    camel.component.http4.connections-per-route=150
    camel.component.http4.max-total-connections=600
    custom.threadpool.profile.poolSize=50
    custom.threadpool.profile.maxPoolSize=150
    custom.threadpool.profile.maxQueueSize=10
    camel.component.http4.connection-time-to-live=12500
    camel.component.http4.connection-request-timeout=1500
    camel.component.http4.socket-timeout=12500
    camel.component.http4.connect-timeout=1500


    kafka.business.exception.uri=direct:send
    sftp.uri.out=direct:sftp

    general.date.formatter=yyyy-MM-dd

    email.uri.out=mock:email

    kafka.rollback.uri=direct:kafka-uri

    # kafka retries
    kafka.retry.uri=direct:kafka-retry

    kafka.retries=3

    kafka.delay=2

    # Business exception
    kafka.exception.topic=business.exception
    business.exception.endpoint=direct:business-exception
